name: CI - Tests & coverage
on: 
  pull_request:
    branches:
      - next
      - main

jobs:
  backend-tests:
    name: Backend (Spring Boot)
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 1.11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        working-directory: back
        run: mvn -B clean package

      - name: Run tests with coverage (JaCoCo)
        working-directory: back
        run: mvn clean verify jacoco:report

      - name: Upload JUnit test reports
        uses: actions/upload-artifact@v4
        with:
          name: backend-junit-reports
          path: back/target/surefire-reports/

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: back/target/site/jacoco/